In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\KIRUBA\Downloads\py-master\py-master\ML\14_naive_bayes\spam.csv")

In [4]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [8]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == "spam" else 0)

In [10]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df['Message'], df['spam'], test_size=0.2)

In [22]:
x_train.shape

(4457,)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

text_to_num = CountVectorizer()
x = text_to_num.fit_transform(x_train)

In [24]:
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [29]:
dir(text_to_num)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [31]:
text_to_num.vocabulary_           # this vocabulary show the position of the words

{'ok': 4925,
 'help': 3402,
 'me': 4413,
 'ask': 1089,
 'if': 3596,
 'she': 6079,
 'working': 7612,
 'tmr': 6938,
 'not': 4837,
 'you': 7725,
 'have': 3359,
 'an': 950,
 'important': 3630,
 'customer': 2130,
 'service': 6038,
 'announcement': 968,
 'from': 3026,
 'premier': 5386,
 'call': 1604,
 'freephone': 2994,
 '0800': 47,
 '542': 555,
 '0578': 17,
 'now': 4852,
 'excellent': 2697,
 'thought': 6873,
 'by': 1588,
 'misundrstud': 4529,
 'frnd': 3017,
 'knw': 3966,
 'hate': 3350,
 'bt': 1534,
 'the': 6820,
 'day': 2184,
 'wen': 7470,
 'll': 4167,
 'truth': 7065,
 'urself': 7224,
 'gn': 3162,
 'babe': 1184,
 'miiiiiiissssssssss': 4481,
 'need': 4735,
 'crave': 2064,
 'geeee': 3104,
 'so': 6283,
 'sad': 5886,
 'without': 7568,
 'love': 4237,
 '74355': 614,
 'xmas': 7672,
 'iscoming': 3750,
 'ur': 7210,
 'awarded': 1167,
 'either': 2554,
 '500': 536,
 'cd': 1697,
 'gift': 3136,
 'vouchers': 7344,
 'free': 2986,
 'entry': 2621,
 '100': 258,
 'weekly': 7458,
 'draw': 2446,
 'txt': 7101,
 '

In [33]:
x = x.toarray()

In [39]:
x[0][x[0] != 0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
np.where(x[0]!=0)

(array([1089, 3402, 3596, 4413, 4837, 4925, 6079, 6938, 7612]),)

In [41]:
from sklearn.naive_bayes import MultinomialNB

clas = MultinomialNB()
clas.fit(x, y_train)

MultinomialNB()

In [42]:
x_test = text_to_num.transform(x_test)

In [43]:
x_test = x_test.toarray()

In [44]:
clas.score(x_test, y_test)

0.9847533632286996

In [56]:
mail = [
    'hi da,  good to see you back',
    '100% cash back, 50% discount',
    'urgently needed an managar',
    'we are hiring, pay 20000 rupees, placement is granted'
]
mail = text_to_num.transform(mail)

In [57]:
clas.predict(mail)

array([0, 1, 0, 0])

In [54]:
mail.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Exercise

In [70]:
df = pd.read_csv(r"C:\Users\KIRUBA\Downloads\IMDB Dataset.csv\IMDB Dataset.csv")

In [71]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [72]:
df.shape

(50000, 2)

In [73]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [74]:
df['analysis'] = df['sentiment'].apply(lambda x: 0 if x == 'positive' else 1)

In [75]:
df.head()

review sentiment  analysis
0  One of the other reviewers has mentioned that ...  positive         0
1  A wonderful little production. <br /><br />The...  positive         0
2  I thought this was a wonderful way to spend ti...  positive         0
3  Basically there's a family where a little boy ...  negative         1
4  Petter Mattei's "Love in the Time of Money" is...  positive         0

In [76]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df['review'], df['analysis'], test_size=0.2, random_state=90)

In [82]:
x_train.shape, y_train.shape, x_test.shape

((40000,), (40000,), (10000,))

In [83]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('countvector', CountVectorizer()),
    ('bayes algo', MultinomialNB())
])

In [84]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('countvector', CountVectorizer()),
                ('bayes algo', MultinomialNB())])

In [85]:
pipe.score(x_test, y_test)

0.8468

In [93]:
reviews = [
    'With strong performances, stunning visuals, and heartfelt storytelling, it is a must-watch for those interested in biographical films and stories of heroism.',
    'i thought the movie is good before watching it, but after watching it i came to conclusion, it is not that much worth.',
    'best movie',
    'somewhat good movie'
]

In [94]:
pipe.predict(reviews)

array([0, 1, 0, 1])